CFLAGS ?=  -Wall -lpthread
all : handout3 handout3-1 handout4

handout3:
	gcc $(CFLAGS) handout3.c -o handout3

handout3-1:
	gcc $(CFLAGS) handout3-1.c -o handout3-1

handout4:
	gcc $(CFLAGS) handout4.c -o handout4

clean:
	rm handout3 handout3-1 handout4

.PHONY: all always
