# The compiler
CC = gcc

CFLAGS = -g -Wall

p1: p1 
	$(CC) $(CFLAGS) -o p1 p1.c

p2: p2
	$(CC) $(CFLAGS) -o p2 p2.c

p3: p3
	$(CC) $(CFLAGS) -o p3 p3.c

p4: p4
	$(CC) $(CFLAGS) -o p4 p4.c
clean:
	$(RM) -f p1 p2 p3
