handout1.s: handout1.c
	gcc -S -c handout1.c

shell.s: shell.c
	gcc -S -c shell.c

shell: shell.c
	gcc -g -o shell shell.c

exectest.s: exectest.c
	gcc -S -c exectest.c

exectest: exectest.c
	gcc -g -o exectest exectest.c
